site_name: Aniurm Notes

theme:
  name: material
  features:
    - content.code.select
  font:
    text: Roboto Mono
    code: JetBrains Mono

nav:
  - Home: "index.md"
  - "课程笔记":
      - MIT6.S081:
          - course_notes/mitos/trap.md
          - course_notes/mitos/lazy.md
          - course_notes/mitos/cow.md
      - 集成电路:
          - course_notes/ic/mos-physic.md
          - course_notes/ic/mos-small-signal.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.arithmatex:
      generic: true

extra_css:
  - css/extra.css

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
