site_name: Aniurm Notes

theme:
  name: material
  features:
    - content.code.select

nav:
  - Home: "index.md"
  - "课程笔记":
      - MIT6.S081:
          - course_notes/mitos/trap.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
