site_name: Aniurm's Notebook

theme:
  name: material
  features:
    - content.code.select
  font:
    text: Roboto Mono
    code: JetBrains Mono

nav:
  - Home: "index.md"
  - "课程笔记":
    - MIT6.S081:
      - Labs:
        - course_notes/mitos/lab/trap.md
        - course_notes/mitos/lab/lazy.md
        - course_notes/mitos/lab/cow.md
        - course_notes/mitos/lab/thread.md
        - course_notes/mitos/lab/locks.md
        - course_notes/mitos/lab/fs.md
        - course_notes/mitos/lab/mmap.md
    - CMU15-445/645:
        - course_notes/cmu15445/primer.md
        - course_notes/cmu15445/buffer-pool.md
        - course_notes/cmu15445/hash-index.md
    - 集成电路:
        - course_notes/ic/mos-physic.md
        - course_notes/ic/mos-small-signal.md
        - course_notes/ic/single-stage-amp.md
    - 深度学习:
        - course_notes/deep-learning/lrnn.md
        - course_notes/deep-learning/cnn.md
    - CS188:
      - Lecture:
        - course_notes/cs188/lecture/Intro-to-AI.md
        - course_notes/cs188/lecture/Uninformed-Search.md
        - course_notes/cs188/lecture/Informed-Search.md
        - course_notes/cs188/lecture/CSPs.md
        - course_notes/cs188/lecture/Search-with-Other-Agents.md
        - course_notes/cs188/lecture/MDPs.md
        - course_notes/cs188/lecture/RL.md
        - course_notes/cs188/lecture/Probability.md
        - course_notes/cs188/lecture/BN-representation.md
        - course_notes/cs188/lecture/BN-Independence.md
        - course_notes/cs188/lecture/BN-Inference.md
        - course_notes/cs188/lecture/BN-Sampling.md
        - course_notes/cs188/lecture/Decision Networks & VPI.md
        - course_notes/cs188/lecture/Hidden Markov Models.md
        - course_notes/cs188/lecture/Particle Filtering.md
        - course_notes/cs188/lecture/ML-Naive Bayes.md
        - course_notes/cs188/lecture/ML-Perceptrons.md
        - course_notes/cs188/lecture/ML-Logistic-Regression.md
        - course_notes/cs188/lecture/ML-Optimization.md
      - Project:
        - course_notes/cs188/project/Reinforcement Learning.md
      - Homework:
        - course_notes/cs188/homework/hw1.md
        - course_notes/cs188/homework/hw2.md
  - 论文阅读:
    - paper_read/virtio-linux-overview.md
    - paper_read/SR-IOV_Notes.md
    - paper_read/Performance_Study_10GbE_NICs_SR-IOV.md
    - paper_read/SR-IOV-KVM-Performance-Impact.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.arithmatex:
      generic: true
  - attr_list
  - md_in_html

extra_css:
  - css/extra.css

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
